# Add a GitHub Check to commits in "master" that specifies the "type" of files that were changed
# ex: "only frontend", "only backed", or "fullstack"
name: meta(deploy)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  files-changed:
    name: detect what files changed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: getsentry/actions/sentry-what-changed@main
